# Generated by Django 6.1 on 2026-08-27 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroGeral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('celular', models.CharField(max_length=20)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('sexo', models.CharField(max_length=20)),
                ('dataNasc', models.DateField(blank=True, null=True)),
                ('estadoCivil', models.CharField(blank=True, max_length=50, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('cep', models.CharField(blank=True, max_length=20, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('lider', models.CharField(blank=True, max_length=255, null=True)),
                ('gc', models.CharField(blank=True, max_length=255, null=True)),
                ('isLider', models.CharField(default='Não', max_length=10)),
                ('dataCadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
