# Generated by Django 6.1 on 2026-08-27 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_cadastrogeral'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoConexao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(blank=True, null=True)),
                ('nome', models.CharField(max_length=150)),
                ('lider', models.CharField(max_length=150)),
                ('lider_supervisor', models.CharField(blank=True, max_length=150, null=True)),
                ('supervisor', models.CharField(blank=True, max_length=150, null=True)),
                ('coordenador', models.CharField(blank=True, max_length=150, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('numero', models.CharField(blank=True, max_length=20, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cep', models.CharField(blank=True, max_length=20, null=True)),
                ('dia_gc', models.CharField(blank=True, max_length=50, null=True)),
                ('horario', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
