# Generated by Django 6.1 on 2026-08-28 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_grupoconexao'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioAvulso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('bannerUrl', models.URLField(blank=True, max_length=1000, null=True)),
                ('configuracaoCampos', models.JSONField(default=dict)),
                ('perguntasCustomizadas', models.JSONField(default=list)),
                ('criadoPor', models.CharField(blank=True, max_length=150, null=True)),
                ('dataCriacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='cadastrogeral',
            name='cpf',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cadastrogeral',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cadastrogeral',
            name='origemFormularioId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cadastrogeral',
            name='origemFormularioNome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cadastrogeral',
            name='respostasCustomizadas',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='cadastrogeral',
            name='celular',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cadastrogeral',
            name='dataCadastro',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='cadastrogeral',
            name='sexo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
