# Generated by Django 6.1 on 2026-08-28 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_filanotificacaopush_ideformulario_ideinscricao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=100, unique=True)),
                ('valor', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='GcLancamentoSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupoId', models.CharField(blank=True, max_length=100, null=True)),
                ('lider', models.CharField(max_length=150)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('dataGc', models.DateField()),
                ('horario', models.CharField(blank=True, max_length=50, null=True)),
                ('statusGc', models.CharField(default='Ocorreu', max_length=50)),
                ('motivoNaoOcorreu', models.TextField(blank=True, null=True)),
                ('membros', models.IntegerField(default=0)),
                ('membrosPresentesIds', models.JSONField(blank=True, default=list)),
                ('visitantes', models.IntegerField(default=0)),
                ('oferta', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('teveOracaoCura', models.CharField(blank=True, max_length=10, null=True)),
                ('qtdCurados', models.IntegerField(default=0)),
                ('testemunhoCura', models.TextField(blank=True, null=True)),
                ('imagemUrl', models.TextField(blank=True, null=True)),
                ('usuarioResponsavel', models.CharField(blank=True, max_length=150, null=True)),
                ('dataCadastro', models.DateTimeField(auto_now_add=True)),
                ('dataAtualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='grupoconexao',
            name='codigo',
        ),
        migrations.AddField(
            model_name='grupoconexao',
            name='anfitriao',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='grupoconexao',
            name='coLider',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='grupoconexao',
            name='generoGc',
            field=models.CharField(default='Misto', max_length=50),
        ),
        migrations.AddField(
            model_name='grupoconexao',
            name='telefoneAnfitriao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='grupoconexao',
            name='telefoneLider',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='grupoconexao',
            name='tipoGc',
            field=models.CharField(default='Família', max_length=50),
        ),
    ]
