# Generated by Django 6.1 on 2026-08-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_configuracaosistema_gclancamentosemanal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscalaMinisterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ministerioId', models.CharField(max_length=255)),
                ('ministerioNome', models.CharField(blank=True, max_length=255, null=True)),
                ('data', models.DateField()),
                ('eventoId', models.CharField(blank=True, max_length=255, null=True)),
                ('evento', models.CharField(blank=True, max_length=255, null=True)),
                ('escalados', models.JSONField(blank=True, default=list)),
                ('dataCriacao', models.DateTimeField(auto_now_add=True)),
                ('dataAtualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'escalas_ministerio',
            },
        ),
        migrations.CreateModel(
            name='EventoMinisterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'eventos_ministerio',
            },
        ),
        migrations.CreateModel(
            name='Ministerio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('lideres', models.JSONField(blank=True, default=list)),
                ('funcoes', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'ministerios',
            },
        ),
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastroId', models.CharField(blank=True, max_length=255, null=True)),
                ('nome', models.CharField(max_length=255)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('sexo', models.CharField(blank=True, max_length=50, null=True)),
                ('liderGc', models.CharField(blank=True, max_length=255, null=True)),
                ('ministerios', models.JSONField(blank=True, default=list)),
                ('dataCadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'voluntarios',
            },
        ),
    ]
