# Generated by Django 6.1 on 2026-08-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_escalaministerio_eventoministerio_ministerio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(default='cafeteria', max_length=50)),
                ('nome', models.CharField(max_length=255)),
                ('telefone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('dataCadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'comercial_clientes',
            },
        ),
        migrations.CreateModel(
            name='ContaPagarComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(default='cafeteria', max_length=50)),
                ('descricao', models.CharField(max_length=255)),
                ('fornecedor', models.CharField(blank=True, max_length=255, null=True)),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('vencimento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='Pendente', max_length=50)),
                ('dataCadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'comercial_contas_pagar',
            },
        ),
        migrations.CreateModel(
            name='EntradaEstoqueComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(default='cafeteria', max_length=50)),
                ('produtoId', models.CharField(max_length=100)),
                ('produtoNome', models.CharField(max_length=255)),
                ('quantidadeAdicionada', models.IntegerField(default=1)),
                ('usuario', models.CharField(default='Sistema', max_length=150)),
                ('dataEntrada', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'comercial_entradas_estoque',
            },
        ),
        migrations.CreateModel(
            name='PendenciaComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(default='cafeteria', max_length=50)),
                ('clienteId', models.CharField(max_length=255)),
                ('itens', models.JSONField(blank=True, default=list)),
                ('valorTotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('formaPagamento', models.CharField(default='Fiado/Pendente', max_length=100)),
                ('pagamentosMult', models.JSONField(blank=True, default=list)),
                ('dataVenda', models.DateTimeField()),
                ('vendedor', models.CharField(default='Sistema PDV', max_length=150)),
                ('estoqueBaixado', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'comercial_pendencias',
            },
        ),
        migrations.CreateModel(
            name='ProdutoComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(default='cafeteria', max_length=50)),
                ('codigo', models.IntegerField(default=0)),
                ('nome', models.CharField(max_length=255)),
                ('codigoBarras', models.CharField(blank=True, max_length=100, null=True)),
                ('precoCusto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('precoVenda', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('estoque', models.IntegerField(default=0)),
                ('imagemUrl', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('dataCadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'comercial_produtos',
            },
        ),
        migrations.CreateModel(
            name='VendaComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(default='cafeteria', max_length=50)),
                ('clienteId', models.CharField(default='Venda Avulsa', max_length=255)),
                ('itens', models.JSONField(blank=True, default=list)),
                ('valorTotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('formaPagamento', models.CharField(default='Dinheiro', max_length=255)),
                ('pagamentosMult', models.JSONField(blank=True, default=list)),
                ('vendedor', models.CharField(default='Sistema PDV', max_length=150)),
                ('dataVenda', models.DateTimeField()),
                ('dataPendenciaOriginal', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comercial_vendas',
            },
        ),
    ]
