# Generated by Django 6.1 on 2026-08-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_clientecomercial_contapagarcomercial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JornadaCadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastroId', models.CharField(blank=True, max_length=100, null=True)),
                ('nome', models.CharField(max_length=255)),
                ('celular', models.CharField(max_length=50)),
                ('etapa', models.IntegerField(default=0)),
                ('exportado', models.BooleanField(default=False)),
                ('cobrancaAtivada', models.BooleanField(default=False)),
                ('cobrancaEnviosCount', models.IntegerField(default=0)),
                ('historicoMensagens', models.JSONField(blank=True, default=list)),
                ('cursosConcluidos', models.JSONField(blank=True, default=list)),
                ('jornadaConcluida', models.BooleanField(default=False)),
                ('dataConclusao', models.DateTimeField(blank=True, null=True)),
                ('dataCadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'jornada_cadastros',
            },
        ),
    ]
