# Generated by Django 6.1 on 2026-08-28 15:27

import usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_jornadacadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jornadacadastro',
            name='id',
            field=models.CharField(default=usuarios.models.gerar_id_jornada, editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
