# Generated by Django 6.1 on 2026-08-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_alter_jornadacadastro_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MidiaBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeEvento', models.CharField(max_length=255)),
                ('linkAcao', models.URLField(blank=True, max_length=1000, null=True)),
                ('dataHorario', models.CharField(blank=True, max_length=255, null=True)),
                ('dataInicio', models.CharField(max_length=20)),
                ('horaInicio', models.CharField(default='00:00', max_length=10)),
                ('dataFim', models.CharField(max_length=20)),
                ('horaFim', models.CharField(default='23:59', max_length=10)),
                ('duracaoSegundos', models.IntegerField(default=4)),
                ('ordem', models.IntegerField(default=99)),
                ('imagemBase64', models.URLField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='MidiaPregacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='unica', max_length=50)),
                ('titulo', models.CharField(max_length=255)),
                ('pregador', models.CharField(blank=True, max_length=255, null=True)),
                ('imagemBase64', models.URLField(max_length=1000)),
                ('audioUrl', models.URLField(blank=True, max_length=1000, null=True)),
                ('mensagens', models.JSONField(blank=True, default=list)),
                ('dataPublicacao', models.CharField(blank=True, max_length=20, null=True)),
                ('horaPublicacao', models.CharField(default='00:00', max_length=10)),
                ('timestampPublicacao', models.BigIntegerField(default=0)),
                ('plays', models.IntegerField(default=0)),
                ('dataCriacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
