# Generated by Django 6.1 on 2026-08-30 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_midiabanner_midiapregacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idemodulo',
            name='gradeCurricular',
        ),
        migrations.RemoveField(
            model_name='ministerio',
            name='funcoes',
        ),
        migrations.RemoveField(
            model_name='ministerio',
            name='lideres',
        ),
        migrations.CreateModel(
            name='IdeModuloAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=255, verbose_name='Tema da Aula')),
                ('exercicioPerguntas', models.JSONField(blank=True, default=list, verbose_name='Perguntas do Exercício (Avançado)')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='usuarios.idemodulo')),
            ],
            options={
                'verbose_name': 'Aula da Grade Curricular',
                'verbose_name_plural': 'Aulas da Grade Curricular',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MinisterioFuncao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Cargo / Função')),
                ('voluntarios', models.JSONField(blank=True, default=list, verbose_name='IDs dos Voluntários')),
                ('ministerio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcoes_rel', to='usuarios.ministerio')),
            ],
            options={
                'verbose_name': 'Cargo / Função',
                'verbose_name_plural': 'Cargos e Equipes',
            },
        ),
        migrations.CreateModel(
            name='MinisterioLider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Líder')),
                ('ministerio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lideres_rel', to='usuarios.ministerio')),
            ],
            options={
                'verbose_name': 'Líder do Ministério',
                'verbose_name_plural': 'Líderes',
            },
        ),
    ]
