# Generated by Django 6.1 on 2026-08-30 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_remove_idemodulo_gradecurricular_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ideformulario',
            name='perguntas',
        ),
        migrations.RemoveField(
            model_name='idemodulo',
            name='perguntas',
        ),
        migrations.RemoveField(
            model_name='idemoduloaula',
            name='exercicioPerguntas',
        ),
        migrations.CreateModel(
            name='IdeFormularioPergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255, verbose_name='Pergunta Customizada')),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas_rel', to='usuarios.ideformulario')),
            ],
            options={
                'verbose_name': 'Pergunta do Formulário',
                'verbose_name_plural': 'Perguntas Customizadas',
            },
        ),
        migrations.CreateModel(
            name='IdeModuloPergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255, verbose_name='Pergunta Exigida')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas_rel', to='usuarios.idemodulo')),
            ],
            options={
                'verbose_name': 'Pergunta do Módulo',
                'verbose_name_plural': 'Perguntas do Módulo',
            },
        ),
    ]
