# Generated by Django 6.1 on 2026-08-31 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_remove_ideformulario_perguntas_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idesala',
            options={'verbose_name': 'Diário de Aula', 'verbose_name_plural': 'Diários de Aulas'},
        ),
        migrations.AlterModelOptions(
            name='ideturma',
            options={'verbose_name': 'Turma do IDE', 'verbose_name_plural': 'Turmas do IDE'},
        ),
        migrations.RemoveField(
            model_name='idesala',
            name='dataCriacao',
        ),
        migrations.RemoveField(
            model_name='idesala',
            name='diaSemana',
        ),
        migrations.RemoveField(
            model_name='idesala',
            name='exercicioAtivo',
        ),
        migrations.RemoveField(
            model_name='idesala',
            name='exercicioPerguntas',
        ),
        migrations.RemoveField(
            model_name='idesala',
            name='justificativas',
        ),
        migrations.RemoveField(
            model_name='idesala',
            name='moduloId',
        ),
        migrations.RemoveField(
            model_name='idesala',
            name='respostasExercicio',
        ),
        migrations.RemoveField(
            model_name='idesala',
            name='turmaId',
        ),
        migrations.RemoveField(
            model_name='idesala',
            name='turmaNome',
        ),
        migrations.RemoveField(
            model_name='ideturma',
            name='abonosReprovacao',
        ),
        migrations.RemoveField(
            model_name='ideturma',
            name='alunos',
        ),
        migrations.RemoveField(
            model_name='ideturma',
            name='formularioId',
        ),
        migrations.RemoveField(
            model_name='ideturma',
            name='removidos',
        ),
        migrations.AddField(
            model_name='idesala',
            name='turma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aulas_rel', to='usuarios.ideturma'),
        ),
        migrations.AlterField(
            model_name='idesala',
            name='data',
            field=models.CharField(max_length=50, verbose_name='Data da Aula'),
        ),
        migrations.AlterField(
            model_name='idesala',
            name='horarioFim',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Término'),
        ),
        migrations.AlterField(
            model_name='idesala',
            name='horarioInicio',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Início'),
        ),
        migrations.AlterField(
            model_name='idesala',
            name='status',
            field=models.CharField(choices=[('Agendada', '🟡 Agendada'), ('Concluída', '🟢 Concluída')], default='Agendada', max_length=50),
        ),
        migrations.AlterField(
            model_name='idesala',
            name='tema',
            field=models.CharField(max_length=255, verbose_name='Tema da Aula'),
        ),
        migrations.AlterField(
            model_name='ideturma',
            name='diaInicio',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Início'),
        ),
        migrations.AlterField(
            model_name='ideturma',
            name='horarioInicio',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Horário'),
        ),
        migrations.AlterField(
            model_name='ideturma',
            name='isEspera',
            field=models.BooleanField(default=False, verbose_name='Fila de Espera?'),
        ),
        migrations.AlterField(
            model_name='ideturma',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome da Turma'),
        ),
        migrations.AlterField(
            model_name='ideturma',
            name='status',
            field=models.CharField(choices=[('Ativa', '🟢 Ativa'), ('Encerrada', '🔴 Encerrada')], default='Ativa', max_length=50),
        ),
        migrations.AlterField(
            model_name='ideturma',
            name='whatsappGrupo',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Link do Grupo'),
        ),
        migrations.CreateModel(
            name='IdeTurmaAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscricaoId', models.CharField(blank=True, max_length=100, null=True)),
                ('alunoNome', models.CharField(max_length=255, verbose_name='Nome do Aluno')),
                ('celular', models.CharField(blank=True, max_length=50, null=True)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos_rel', to='usuarios.ideturma')),
            ],
            options={
                'verbose_name': 'Aluno Matriculado',
                'verbose_name_plural': 'Alunos da Turma',
            },
        ),
    ]
